using System;
using System.IO;
/* 这些用不上
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
*/

/* おす! こにんちわ! こんばんわ! 这里是说明:
 * 这里嵌套命名空间是为了方便管理(大概).因为
 * 以后(并不)可能写其他的东西,所以先做个分类
 * 引用方法很简单..如果嫌麻烦可以用神奇using
 * 不仅嵌套命名空间我还嵌套了类.所以记得不要
 * 忘记Spawn.*** 其中RA2.Ini.Spawn.Write方法
 * 是将类储存的内容写出到指定的INI里..初始化
 * 方法为RA2.Ini.Spawn.SpawnPath = SpawnPath
 * 写入直接调用Write方法就行..其他的字段可空
 * 如果留空则不会写入到ini文件中..这里用的是
 * 流输出写入到ini,不同于之前的写INI键值以及
 * public bool a;的存在,这个是写入的开关..请
 * 在使用的时候记得设置为true.不然将会被忽略
 * 结尾依旧不明意义的键..依旧用的CNCNet5.dll
 * (这次写的比之前写的好多了) ぜかまし です!
 */// Last edited at : 2019.7.6 19:01:31 SAT

namespace RA2.Ini
{
    /// <summary>
    /// SPAWN.INI class
    /// </summary>
    public class Spawn
    {
        /// <summary>
        /// SPAWN.INI Path
        /// </summary>
        public String SpawnPath;//= AppDomain.CurrentDomain.BaseDirectory+"spawn.ini";
        // 
        public Other Other1 = new Other();
        public Other Other2 = new Other();
        public Other Other3 = new Other();
        public Other Other4 = new Other();
        public Other Other5 = new Other();
        public Other Other6 = new Other();
        public Other Other7 = new Other();
        public Alliances Multi1_Alliances = new Alliances();
        public Alliances Multi2_Alliances = new Alliances();
        public Alliances Multi3_Alliances = new Alliances();
        public Alliances Multi4_Alliances = new Alliances();
        public Alliances Multi5_Alliances = new Alliances();
        public Alliances Multi6_Alliances = new Alliances();
        public Alliances Multi7_Alliances = new Alliances();
        public Alliances Multi8_Alliances = new Alliances();

        public SettingsA Settings = new SettingsA();
        public SpawnLocationsA SpawnLocations = new SpawnLocationsA();
        public HouseCountriesA HouseCountries = new HouseCountriesA();
        public HouseColorsA HouseColors = new HouseColorsA();
        public HouseHandicapsA HouseHandicaps = new HouseHandicapsA();
        public TunnelA Tunnel = new TunnelA();

        public Spawn(string IniPath) { SpawnPath = IniPath; }
        public Spawn() { SpawnPath = AppDomain.CurrentDomain.BaseDirectory + "spawn.ini"; }
        /// <summary>
        /// writer the spawn.ini
        /// </summary>
        public void Write()
        {
            // Open Stream
            FileStream fs = new FileStream(SpawnPath, FileMode.Create);
            StreamWriter sw = new StreamWriter(fs);
            // Write 

            sw.Write("; generated by Crape Client\r\n");
            // sw.Write("; 内容\r\n");
            #region Settings
            sw.Write("[Settings]\r\n");
            if (Settings.Name != null)
                sw.Write("Name=" + Settings.Name + "\r\n");
            if (Settings.CustomLoadScreen != null)
                sw.Write("CustomLoadScreen=" + Settings.CustomLoadScreen + "\r\n");
            if (Settings.SaveGameName != null)
                sw.Write("SaveGameName=" + Settings.SaveGameName + "\r\n");
            if (Settings.UIGameMode != null)
                sw.Write("UIGameMode=" + Settings.UIGameMode + "\r\n");
            if (Settings.UIMapName != null)
                sw.Write("UIMapName=" + Settings.UIMapName + "\r\n");
            if (Settings.MapHash != null)
                sw.Write("MapHash=" + Settings.MapHash + "\r\n");
            if (Settings.Scenario != null)
                sw.Write("Scenario=" + Settings.Scenario + "\r\n");

            if (Settings.UnitCount != null)
                sw.Write("UnitCount=" + Convert.ToString(Settings.UnitCount) + "\r\n");
            if (Settings.GameSpeed != null)
                sw.Write("GameSpeed=" + Convert.ToString(Settings.GameSpeed) + "\r\n");
            if (Settings.TechLevel != null)
                sw.Write("TechLevel=" + Convert.ToString(Settings.TechLevel) + "\r\n");
            if (Settings.AIPlayers != null)
                sw.Write("AIPlayers=" + Convert.ToString(Settings.AIPlayers) + "\r\n");
            if (Settings.AIDifficulty != null)
                sw.Write("AIDifficulty=" + Convert.ToString(Settings.AIDifficulty) + "\r\n");
            if (Settings.Side != null)
                sw.Write("Side=" + Convert.ToString(Settings.Side) + "\r\n");
            if (Settings.Color != null)
                sw.Write("Color=" + Convert.ToString(Settings.Color) + "\r\n");
            if (Settings.DifficultyModeComputer != null)
                sw.Write("DifficultyModeComputer=" + Convert.ToString(Settings.DifficultyModeComputer) + "\r\n");
            if (Settings.DifficultyModeHuman != null)
                sw.Write("DifficultyModeHuman=" + Convert.ToString(Settings.DifficultyModeHuman) + "\r\n");
            if (Settings.PlayerCount != null)
                sw.Write("PlayerCount=" + Convert.ToString(Settings.PlayerCount) + "\r\n");
            if (Settings.GameMode != null)
                sw.Write("GameMode=" + Convert.ToString(Settings.GameMode) + "\r\n");
            if (Settings.Credits != null)
                sw.Write("Credits=" + Convert.ToString(Settings.Credits) + "\r\n");
            if (Settings.GameID != null)
                sw.Write("GameID=" + Convert.ToString(Settings.GameID) + "\r\n");
            if (Settings.Seed != null)
                sw.Write("Seed=" + Convert.ToString(Settings.Seed) + "\r\n");
            if (Settings.Port != null)
                sw.Write("Port=" + Convert.ToString(Settings.Port) + "\r\n");

            if (Settings.LoadSaveGame == true) sw.Write("LoadSaveGame=1\r\n");

            if (Settings.ShortGame == true) sw.Write("ShortGame=1\r\n");

            if (Settings.Creates == true) sw.Write("Creates=1\r\n");

            if (Settings.AlliesAllowed == true) sw.Write("AlliesAllowed=1\r\n");

            if (Settings.MultiEngineer == true) sw.Write("MultiEngineer=1\r\n");

            if (Settings.MCVRedeploy == true) sw.Write("MCVRedeploy=1\r\n");
            if (Settings.MCVRedeploy == false) sw.Write("MCVRedeploy=0\r\n");
            if (Settings.FogOfWar == true) sw.Write("FogOfWar=1\r\n");
            if (Settings.FogOfWar == false) sw.Write("FogOfWar=0\r\n");
            if (Settings.BridgeDestroy == true) sw.Write("BridgeDestroy=1\r\n");

            if (Settings.AutoDeployMCV == true) sw.Write("AutoDeployMCV=1\r\n");

            if (Settings.SkipScoreScreen == true) sw.Write("SkipScoreScreen=1\r\n");

            if (Settings.IsSinglePlayer == true) sw.Write("IsSinglePlayer=1\r\n");
            if (Settings.IsSinglePlayer == false) sw.Write("IsSinglePlayer=0\r\n");
            if (Settings.Firestorm == true) sw.Write("Firestorm=1\r\n");
            if (Settings.Firestorm == false) sw.Write("Firestorm=0\r\n");
            if (Settings.BuildOffAlly == true) sw.Write("BuildOffAlly=1\r\n");
            if (Settings.BuildOffAlly == false) sw.Write("BuildOffAlly=0\r\n");
            if (Settings.IsSpectator == true) sw.Write("IsSpectator=1\r\n");
            if (Settings.IsSpectator == false) sw.Write("IsSpectator=0\r\n");
            if (Settings.Bases == true) sw.Write("Bases=1\r\n");
            if (Settings.Bases == false) sw.Write("Bases=0\r\n");
            if (Settings.SidebarHack == true) sw.Write("SidebarHack=1\r\n");
            if (Settings.SidebarHack == false) sw.Write("SidebarHack=0\r\n");
            if (Settings.Host == true) sw.Write("Host=1\r\n");
            if (Settings.Host == false) sw.Write("Host=0\r\n");
            if (Settings.Superweapons == true) sw.Write("Superweapons=1\r\n");
            if (Settings.Superweapons == false) sw.Write("Superweapons=0\r\n");
            if (Settings.AttackNeutralUnits == true) sw.Write("AttackNeutralUnits=1\r\n");
            if (Settings.AttackNeutralUnits == false) sw.Write("AttackNeutralUnits=0\r\n");
            sw.Write("\r\n\r\n\r\n");
            #endregion

            #region AISettings
            if (SpawnLocations.Multi1 != null && 
                SpawnLocations.Multi2 != null && 
                SpawnLocations.Multi3 != null && 
                SpawnLocations.Multi4 != null && 
                SpawnLocations.Multi5 != null && 
                SpawnLocations.Multi6 != null && 
                SpawnLocations.Multi7 != null )
                sw.Write("[SpawnLocations]\r\n");
            if (SpawnLocations.Multi1 != null) sw.Write("Multi1=" + Convert.ToString(SpawnLocations.Multi1) + "\r\n");
            if (SpawnLocations.Multi2 != null) sw.Write("Multi2=" + Convert.ToString(SpawnLocations.Multi2) + "\r\n");
            if (SpawnLocations.Multi3 != null) sw.Write("Multi3=" + Convert.ToString(SpawnLocations.Multi3) + "\r\n");
            if (SpawnLocations.Multi4 != null) sw.Write("Multi4=" + Convert.ToString(SpawnLocations.Multi4) + "\r\n");
            if (SpawnLocations.Multi5 != null) sw.Write("Multi5=" + Convert.ToString(SpawnLocations.Multi5) + "\r\n");
            if (SpawnLocations.Multi6 != null) sw.Write("Multi6=" + Convert.ToString(SpawnLocations.Multi6) + "\r\n");
            if (SpawnLocations.Multi7 != null) sw.Write("Multi7=" + Convert.ToString(SpawnLocations.Multi7) + "\r\n");
            sw.Write("\r\n\r\n\r\n");
            // Countries
            if (HouseCountries.Multi1 != null &&
                HouseCountries.Multi2 != null &&
                HouseCountries.Multi3 != null &&
                HouseCountries.Multi4 != null &&
                HouseCountries.Multi5 != null &&
                HouseCountries.Multi6 != null &&
                HouseCountries.Multi7 != null)
                sw.Write("[HouseCountries]\r\n");
            if (HouseCountries.Multi1 != null) sw.Write("Multi1=" + Convert.ToString(HouseCountries.Multi1) + "\r\n");
            if (HouseCountries.Multi2 != null) sw.Write("Multi2=" + Convert.ToString(HouseCountries.Multi2) + "\r\n");
            if (HouseCountries.Multi3 != null) sw.Write("Multi3=" + Convert.ToString(HouseCountries.Multi3) + "\r\n");
            if (HouseCountries.Multi4 != null) sw.Write("Multi4=" + Convert.ToString(HouseCountries.Multi4) + "\r\n");
            if (HouseCountries.Multi5 != null) sw.Write("Multi5=" + Convert.ToString(HouseCountries.Multi5) + "\r\n");
            if (HouseCountries.Multi6 != null) sw.Write("Multi6=" + Convert.ToString(HouseCountries.Multi6) + "\r\n");
            if (HouseCountries.Multi7 != null) sw.Write("Multi7=" + Convert.ToString(HouseCountries.Multi7) + "\r\n");
            sw.Write("\r\n\r\n\r\n");
            // Colors
            if (HouseColors.Multi1 != null &&
                HouseColors.Multi2 != null &&
                HouseColors.Multi3 != null &&
                HouseColors.Multi4 != null &&
                HouseColors.Multi5 != null &&
                HouseColors.Multi6 != null &&
                HouseColors.Multi7 != null)
                sw.Write("[HouseColors]\r\n");
            if (HouseColors.Multi1 != null) sw.Write("Multi1=" + Convert.ToString(HouseColors.Multi1) + "\r\n");
            if (HouseColors.Multi2 != null) sw.Write("Multi2=" + Convert.ToString(HouseColors.Multi2) + "\r\n");
            if (HouseColors.Multi3 != null) sw.Write("Multi3=" + Convert.ToString(HouseColors.Multi3) + "\r\n");
            if (HouseColors.Multi4 != null) sw.Write("Multi4=" + Convert.ToString(HouseColors.Multi4) + "\r\n");
            if (HouseColors.Multi5 != null) sw.Write("Multi5=" + Convert.ToString(HouseColors.Multi5) + "\r\n");
            if (HouseColors.Multi6 != null) sw.Write("Multi6=" + Convert.ToString(HouseColors.Multi6) + "\r\n");
            if (HouseColors.Multi7 != null) sw.Write("Multi7=" + Convert.ToString(HouseColors.Multi7) + "\r\n");
            sw.Write("\r\n\r\n\r\n");
            // Handicaps
            if (HouseHandicaps.Multi1 != null &&
                HouseHandicaps.Multi2 != null &&
                HouseHandicaps.Multi3 != null &&
                HouseHandicaps.Multi4 != null &&
                HouseHandicaps.Multi5 != null &&
                HouseHandicaps.Multi6 != null &&
                HouseHandicaps.Multi7 != null)
                sw.Write("[HouseHandicaps]\r\n");
            if (HouseHandicaps.Multi1 != null) sw.Write("Multi1=" + Convert.ToString(HouseHandicaps.Multi1) + "\r\n");
            if (HouseHandicaps.Multi2 != null) sw.Write("Multi2=" + Convert.ToString(HouseHandicaps.Multi2) + "\r\n");
            if (HouseHandicaps.Multi3 != null) sw.Write("Multi3=" + Convert.ToString(HouseHandicaps.Multi3) + "\r\n");
            if (HouseHandicaps.Multi4 != null) sw.Write("Multi4=" + Convert.ToString(HouseHandicaps.Multi4) + "\r\n");
            if (HouseHandicaps.Multi5 != null) sw.Write("Multi5=" + Convert.ToString(HouseHandicaps.Multi5) + "\r\n");
            if (HouseHandicaps.Multi6 != null) sw.Write("Multi6=" + Convert.ToString(HouseHandicaps.Multi6) + "\r\n");
            if (HouseHandicaps.Multi7 != null) sw.Write("Multi7=" + Convert.ToString(HouseHandicaps.Multi7) + "\r\n");
            sw.Write("\r\n\r\n\r\n");
            #endregion

            // Servers Setting
            if (Tunnel.HaveTunnel)
            {
                sw.Write("[Tunnel]\r\n");
                sw.Write("Ip=" + Tunnel.Ip + "\r\n");
                sw.Write("Port=" + Convert.ToString(Tunnel.Port) + "\r\n");
                sw.Write("\r\n\r\n\r\n");
            }

            #region Other Player
            if (Other1.a)
            {
                sw.Write("[Other1]\r\n");
                sw.Write("Name=" + Other1.Name + "\r\n");
                sw.Write("Side=" + Convert.ToString(Other1.Side) + "\r\n");
                sw.Write("IsSpectator=" + Convert.ToString(Other1.IsSpectator) + "\r\n");
                sw.Write("Color=" + Convert.ToString(Other1.Color) + "\r\n");
                sw.Write("Ip=" + Other1.Ip + "\r\n");
                sw.Write("Port=" + Convert.ToString(Other1.Port) + "\r\n");
                sw.Write("\r\n");
            }
            if (Other2.a)
            {
                sw.Write("[Other2]\r\n");
                sw.Write("Name=" + Other2.Name + "\r\n");
                sw.Write("Side=" + Convert.ToString(Other2.Side) + "\r\n");
                sw.Write("IsSpectator=" + Convert.ToString(Other2.IsSpectator) + "\r\n");
                sw.Write("Color=" + Convert.ToString(Other2.Color) + "\r\n");
                sw.Write("Ip=" + Other2.Ip + "\r\n");
                sw.Write("Port=" + Convert.ToString(Other2.Port) + "\r\n");
                sw.Write("\r\n");
            }
            if (Other3.a)
            {
                sw.Write("[Other3]\r\n");
                sw.Write("Name=" + Other3.Name + "\r\n");
                sw.Write("Side=" + Convert.ToString(Other3.Side) + "\r\n");
                sw.Write("IsSpectator=" + Convert.ToString(Other3.IsSpectator) + "\r\n");
                sw.Write("Color=" + Convert.ToString(Other3.Color) + "\r\n");
                sw.Write("Ip=" + Other3.Ip + "\r\n");
                sw.Write("Port=" + Convert.ToString(Other3.Port) + "\r\n");
                sw.Write("\r\n");
            }
            if (Other4.a)
            {
                sw.Write("[Other4]\r\n");
                sw.Write("Name=" + Other4.Name + "\r\n");
                sw.Write("Side=" + Convert.ToString(Other4.Side) + "\r\n");
                sw.Write("IsSpectator=" + Convert.ToString(Other4.IsSpectator) + "\r\n");
                sw.Write("Color=" + Convert.ToString(Other4.Color) + "\r\n");
                sw.Write("Ip=" + Other4.Ip + "\r\n");
                sw.Write("Port=" + Convert.ToString(Other4.Port) + "\r\n");
                sw.Write("\r\n");
            }
            if (Other5.a)
            {
                sw.Write("[Other5]\r\n");
                sw.Write("Name=" + Other5.Name + "\r\n");
                sw.Write("Side=" + Convert.ToString(Other5.Side) + "\r\n");
                sw.Write("IsSpectator=" + Convert.ToString(Other5.IsSpectator) + "\r\n");
                sw.Write("Color=" + Convert.ToString(Other5.Color) + "\r\n");
                sw.Write("Ip=" + Other5.Ip + "\r\n");
                sw.Write("Port=" + Convert.ToString(Other5.Port) + "\r\n");
                sw.Write("\r\n");
            }
            if (Other6.a)
            {
                sw.Write("[Other6]\r\n");
                sw.Write("Name=" + Other6.Name + "\r\n");
                sw.Write("Side=" + Convert.ToString(Other6.Side) + "\r\n");
                sw.Write("IsSpectator=" + Convert.ToString(Other6.IsSpectator) + "\r\n");
                sw.Write("Color=" + Convert.ToString(Other6.Color) + "\r\n");
                sw.Write("Ip=" + Other6.Ip + "\r\n");
                sw.Write("Port=" + Convert.ToString(Other6.Port) + "\r\n");
                sw.Write("\r\n");
            }
            if (Other7.a)
            {
                sw.Write("[Other7]\r\n");
                sw.Write("Name=" + Other7.Name + "\r\n");
                sw.Write("Side=" + Convert.ToString(Other7.Side) + "\r\n");
                sw.Write("IsSpectator=" + Convert.ToString(Other7.IsSpectator) + "\r\n");
                sw.Write("Color=" + Convert.ToString(Other7.Color) + "\r\n");
                sw.Write("Ip=" + Other7.Ip + "\r\n");
                sw.Write("Port=" + Convert.ToString(Other7.Port) + "\r\n");
                sw.Write("\r\n");
            }
            #endregion

            #region Player Alliances
            if (Multi1_Alliances.a)
            {
                sw.Write("[Multi1_Alliances]\r\n");
                sw.Write("HouseAllyOne=" + Convert.ToString(Multi1_Alliances.HouseAllyOne) + "\r\n");
                sw.Write("HouseAllyTwe=" + Convert.ToString(Multi1_Alliances.HouseAllyTwe) + "\r\n");
                sw.Write("HouseAllyThree=" + Convert.ToString(Multi1_Alliances.HouseAllyThree) + "\r\n");
                sw.Write("HouseAllyFour=" + Convert.ToString(Multi1_Alliances.HouseAllyFour) + "\r\n");
                sw.Write("HouseAllyFive=" + Convert.ToString(Multi1_Alliances.HouseAllyFive) + "\r\n");
                sw.Write("HouseAllySix=" + Convert.ToString(Multi1_Alliances.HouseAllySix) + "\r\n");
                sw.Write("HouseAllySeven=" + Convert.ToString(Multi1_Alliances.HouseAllySeven) + "\r\n");
                sw.Write("\r\n");
            }
            if (Multi2_Alliances.a)
            {
                sw.Write("[Multi2_Alliances]\r\n");
                sw.Write("HouseAllyOne=" + Convert.ToString(Multi2_Alliances.HouseAllyOne) + "\r\n");
                sw.Write("HouseAllyTwe=" + Convert.ToString(Multi2_Alliances.HouseAllyTwe) + "\r\n");
                sw.Write("HouseAllyThree=" + Convert.ToString(Multi2_Alliances.HouseAllyThree) + "\r\n");
                sw.Write("HouseAllyFour=" + Convert.ToString(Multi2_Alliances.HouseAllyFour) + "\r\n");
                sw.Write("HouseAllyFive=" + Convert.ToString(Multi2_Alliances.HouseAllyFive) + "\r\n");
                sw.Write("HouseAllySix=" + Convert.ToString(Multi2_Alliances.HouseAllySix) + "\r\n");
                sw.Write("HouseAllySeven=" + Convert.ToString(Multi2_Alliances.HouseAllySeven) + "\r\n");
                sw.Write("\r\n");
            }
            if (Multi3_Alliances.a)
            {
                sw.Write("[Multi3_Alliances]\r\n");
                sw.Write("HouseAllyOne=" + Convert.ToString(Multi3_Alliances.HouseAllyOne) + "\r\n");
                sw.Write("HouseAllyTwe=" + Convert.ToString(Multi3_Alliances.HouseAllyTwe) + "\r\n");
                sw.Write("HouseAllyThree=" + Convert.ToString(Multi3_Alliances.HouseAllyThree) + "\r\n");
                sw.Write("HouseAllyFour=" + Convert.ToString(Multi3_Alliances.HouseAllyFour) + "\r\n");
                sw.Write("HouseAllyFive=" + Convert.ToString(Multi3_Alliances.HouseAllyFive) + "\r\n");
                sw.Write("HouseAllySix=" + Convert.ToString(Multi3_Alliances.HouseAllySix) + "\r\n");
                sw.Write("HouseAllySeven=" + Convert.ToString(Multi3_Alliances.HouseAllySeven) + "\r\n");
                sw.Write("\r\n");
            }
            if (Multi4_Alliances.a)
            {
                sw.Write("[Multi4_Alliances]\r\n");
                sw.Write("HouseAllyOne=" + Convert.ToString(Multi4_Alliances.HouseAllyOne) + "\r\n");
                sw.Write("HouseAllyTwe=" + Convert.ToString(Multi4_Alliances.HouseAllyTwe) + "\r\n");
                sw.Write("HouseAllyThree=" + Convert.ToString(Multi4_Alliances.HouseAllyThree) + "\r\n");
                sw.Write("HouseAllyFour=" + Convert.ToString(Multi4_Alliances.HouseAllyFour) + "\r\n");
                sw.Write("HouseAllyFive=" + Convert.ToString(Multi4_Alliances.HouseAllyFive) + "\r\n");
                sw.Write("HouseAllySix=" + Convert.ToString(Multi4_Alliances.HouseAllySix) + "\r\n");
                sw.Write("HouseAllySeven=" + Convert.ToString(Multi4_Alliances.HouseAllySeven) + "\r\n");
                sw.Write("\r\n");
            }
            if (Multi5_Alliances.a)
            {
                sw.Write("[Multi5_Alliances]\r\n");
                sw.Write("HouseAllyOne=" + Convert.ToString(Multi5_Alliances.HouseAllyOne) + "\r\n");
                sw.Write("HouseAllyTwe=" + Convert.ToString(Multi5_Alliances.HouseAllyTwe) + "\r\n");
                sw.Write("HouseAllyThree=" + Convert.ToString(Multi5_Alliances.HouseAllyThree) + "\r\n");
                sw.Write("HouseAllyFour=" + Convert.ToString(Multi5_Alliances.HouseAllyFour) + "\r\n");
                sw.Write("HouseAllyFive=" + Convert.ToString(Multi5_Alliances.HouseAllyFive) + "\r\n");
                sw.Write("HouseAllySix=" + Convert.ToString(Multi5_Alliances.HouseAllySix) + "\r\n");
                sw.Write("HouseAllySeven=" + Convert.ToString(Multi5_Alliances.HouseAllySeven) + "\r\n");
                sw.Write("\r\n");
            }
            if (Multi6_Alliances.a)
            {
                sw.Write("[Multi6_Alliances]\r\n");
                sw.Write("HouseAllyOne=" + Convert.ToString(Multi6_Alliances.HouseAllyOne) + "\r\n");
                sw.Write("HouseAllyTwe=" + Convert.ToString(Multi6_Alliances.HouseAllyTwe) + "\r\n");
                sw.Write("HouseAllyThree=" + Convert.ToString(Multi6_Alliances.HouseAllyThree) + "\r\n");
                sw.Write("HouseAllyFour=" + Convert.ToString(Multi6_Alliances.HouseAllyFour) + "\r\n");
                sw.Write("HouseAllyFive=" + Convert.ToString(Multi6_Alliances.HouseAllyFive) + "\r\n");
                sw.Write("HouseAllySix=" + Convert.ToString(Multi6_Alliances.HouseAllySix) + "\r\n");
                sw.Write("HouseAllySeven=" + Convert.ToString(Multi6_Alliances.HouseAllySeven) + "\r\n");
                sw.Write("\r\n");
            }
            if (Multi7_Alliances.a)
            {
                sw.Write("[Multi7_Alliances]\r\n");
                sw.Write("HouseAllyOne=" + Convert.ToString(Multi7_Alliances.HouseAllyOne) + "\r\n");
                sw.Write("HouseAllyTwe=" + Convert.ToString(Multi7_Alliances.HouseAllyTwe) + "\r\n");
                sw.Write("HouseAllyThree=" + Convert.ToString(Multi7_Alliances.HouseAllyThree) + "\r\n");
                sw.Write("HouseAllyFour=" + Convert.ToString(Multi7_Alliances.HouseAllyFour) + "\r\n");
                sw.Write("HouseAllyFive=" + Convert.ToString(Multi7_Alliances.HouseAllyFive) + "\r\n");
                sw.Write("HouseAllySix=" + Convert.ToString(Multi7_Alliances.HouseAllySix) + "\r\n");
                sw.Write("HouseAllySeven=" + Convert.ToString(Multi7_Alliances.HouseAllySeven) + "\r\n");
                sw.Write("\r\n");
            }
            if (Multi8_Alliances.a)
            {
                sw.Write("[Multi8_Alliances]\r\n");
                sw.Write("HouseAllyOne=" + Convert.ToString(Multi8_Alliances.HouseAllyOne) + "\r\n");
                sw.Write("HouseAllyTwe=" + Convert.ToString(Multi8_Alliances.HouseAllyTwe) + "\r\n");
                sw.Write("HouseAllyThree=" + Convert.ToString(Multi8_Alliances.HouseAllyThree) + "\r\n");
                sw.Write("HouseAllyFour=" + Convert.ToString(Multi8_Alliances.HouseAllyFour) + "\r\n");
                sw.Write("HouseAllyFive=" + Convert.ToString(Multi8_Alliances.HouseAllyFive) + "\r\n");
                sw.Write("HouseAllySix=" + Convert.ToString(Multi8_Alliances.HouseAllySix) + "\r\n");
                sw.Write("HouseAllySeven=" + Convert.ToString(Multi8_Alliances.HouseAllySeven) + "\r\n");
                sw.Write("\r\n");
            }
            #endregion
            //*/
            // Clean Cache
            sw.Flush();
            // Close Stream
            sw.Close();
            fs.Close();
        }
        /// <summary>
        /// 库版本
        /// </summary>
        /// <returns>库版本信息</returns>
        public static string Version()
        {
            return "1.0.0.80";//"20190715-19:30";
        }

        #region Settings

        /// <summary>
        /// 主要设定
        /// </summary>
        public class SettingsA // locale settings
        {
            public Byte? UnitCount;// 初始单位数量
            public Byte? GameSpeed;// 游戏速度控制 0-6
            public Byte? TechLevel;// 科技等级1-10
            public Byte? AIPlayers;// AI玩家数量
            public Byte? AIDifficulty;// AI难度
            public Byte? Side;// 作战方-国家
            public Byte? Color;// 作战方所属颜色
            public Byte? DifficultyModeComputer;// 计算机难度模式
            public Byte? DifficultyModeHuman;// 人类难度模式
            public Byte? PlayerCount;// 游戏者数量
            public Byte? GameMode;// 游戏模式
            public UInt32? Credits;// 初始资金
            public UInt64? GameID;// 游戏ID--?
            public UInt64? Seed;// --?
            public Int64? Port;// --?
            public Boolean? ShortGame;// 快速游戏
            public Boolean? Creates;// 升级工具箱
            public Boolean? AlliesAllowed;// 允许游戏中结萌
            public Boolean? MultiEngineer;// 多位攻城狮
            public Boolean? MCVRedeploy;// MCV可重新部署
            public Boolean? FogOfWar;// 启用战争迷雾 注:战争迷雾不同于黑幕..战争迷雾透光
            public Boolean? BridgeDestroy;// 桥梁可被破坏
            public Boolean? AutoDeployMCV;// 自动部署MCV--?
            public Boolean? SkipScoreScreen;// 跳过评分屏
            public Boolean? IsSinglePlayer;// 是单人游戏
            public Boolean? Firestorm;// 火风暴--?
            public Boolean? BuildOffAlly;// 可在萌友旁建造
            public Boolean? IsSpectator;// 是T.E.O.T.S.Y.
            public Boolean? Bases;// 基地--?
            public Boolean? SidebarHack;// 边栏hack--?
            public Boolean? Host;// 是主机
            public Boolean? Superweapons;// 炒鸡武器
            public Boolean? AttackNeutralUnits;// 攻击中立单位
            public Boolean? LoadSaveGame;// 是否加载已储存游戏
            public String Scenario;// 设置场景(游戏地图文件)
            public String Name;// 游戏者名
            public String CustomLoadScreen;// 加载自定义载入画面--?
            public String UIGameMode;// 
            public String UIMapName;//
            public String MapHash;//
            public String SaveGameName;// 要加载的以保存的存档名

        }
        /// <summary>
        /// AI 初始地点设置
        /// </summary>
        public class SpawnLocationsA // AI spawn set
        {
            public Byte? Multi1;
            public Byte? Multi2;
            public Byte? Multi3;
            public Byte? Multi4;
            public Byte? Multi5;
            public Byte? Multi6;
            public Byte? Multi7;
        }
        /// <summary>
        /// AI 国家设定
        /// </summary>
        public class HouseCountriesA // AI countrie set
        {
            public Byte? Multi1;
            public Byte? Multi2;
            public Byte? Multi3;
            public Byte? Multi4;
            public Byte? Multi5;
            public Byte? Multi6;
            public Byte? Multi7;
        }
        /// <summary>
        /// AI 颜色设置
        /// </summary>
        public class HouseColorsA // AI colour set
        {
            public Byte? Multi1;
            public Byte? Multi2;
            public Byte? Multi3;
            public Byte? Multi4;
            public Byte? Multi5;
            public Byte? Multi6;
            public Byte? Multi7;
        }
        /// <summary>
        /// AI 困难设置
        /// </summary>
        public class HouseHandicapsA // AI Handicaps
        {
            public Byte? Multi1;
            public Byte? Multi2;
            public Byte? Multi3;
            public Byte? Multi4;
            public Byte? Multi5;
            public Byte? Multi6;
            public Byte? Multi7;
        }
        public class TunnelA // servers config
        {
            public Boolean HaveTunnel; 
            public String Ip;
            public UInt16 Port;

        }
        /// <summary>
        /// 其他玩家设置
        /// </summary>
        public class Other // Other*
        {
            public Boolean a; // is include
            public String Name;
            public Byte? Side;
            public Boolean? IsSpectator;
            public Byte? Color;
            public String Ip = "0.0.0.0";
            public Int64? Port;
        }
        /// <summary>
        /// 玩家结盟设置
        /// </summary>
        public class Alliances // Multi*_Alliances
        {
            public Boolean a; // is include
            public Byte? HouseAllyOne;
            public Byte? HouseAllyTwe;
            public Byte? HouseAllyThree;
            public Byte? HouseAllyFour;
            public Byte? HouseAllyFive;
            public Byte? HouseAllySix;
            public Byte? HouseAllySeven;
        }
        #endregion


    }
}
/* 意义不明配置项(键):
 * MultipleFactory
 * SharedControl
 * FrameSendRate
 * MaxAhead
 * PreCalcMaxAhead
 * PreCalcFrameRate
 * Protocol
 * RunAutoSS
 * AutoSaveGame
 * TeamName
 * AimableSams
 * IntegrateMumble
 * AttackNeutralUnits
 * ScrapMetal
 * QuickMatch
 * CoachMode
 * AutoSurrender
 *
 * Spawn1
 * Spawn2
 * Spawn3
 * Spawn4
 * Spawn5
 * Spawn6
 * Spawn7
 * Spawn8
 *
 * AllyBySpawnLocation
 * UseGraphicsPatch
 * ForceLowestDetailLevel
 * InvisibleSouthDisruptorWave
 * NoCD
 * SetProcessAffinityMask
 * SingleProcAffinity
 * 
 * debugplayer
 * debugplayer2
 */
